import Component from 'ember-component';
import hbs from 'htmlbars-inline-precompile';

/**
 * Docs Page class header. Contains class name with a link to source file for
 * class.
 * @class FountainHead.Class.Header
 * @constructor
 * @extends Ember.Component
 */
export default Component.extend({

  // Passed Properties
  // ---------------------------------------------------------------------------

  /**
   * File name for the JSON of this file. Used for link to for source.
   * @property fileJSON
   * @type {string}
   * @default ''
   */
  fileJSON: '',
  /**
   * Name of the class. Is generated by the `@constructor` tag.
   * @property name
   * @type {string}
   * @default ''
   */
  name: '',

  // Properties
  // ---------------------------------------------------------------------------
  tagName: 'h2',
  classNames: ['fountain-doc-header'],

  // Layout
  // ---------------------------------------------------------------------------
  layout: hbs`
    {{! @TODO Handle Class/Module/Namespace }}
    {{name}} Class
    <small>
      {{! @TODO: Link component needed to handle external vs internal file links }}
      {{#link-to 'docs.files' fileJSON className='source-icon'}}
        [source]
      {{/link-to}}
    </small>
  `
});
