import Component from 'ember-component';
import hbs from 'htmlbars-inline-precompile';

/**
 * Fountainhead `/doc/file` page component
 * @class FountainheadPages.File
 * @constructor
 * @extends Ember.Component
 */
export default Component.extend({

  /**
   * JSON stringified file generated by documentation script.
   * @property file
   * @type {string}
   * @default ''
   */
  file: '',

  // Layout
  // ---------------------------------------------------------------------------
  layout: hbs`
    <h2 class='fh-page-header'>{{file.file}}</h2>
    {{{file.content}}}
  `
});
