import hbs from 'htmlbars-inline-precompile';
import BasePage from './base-page';

/**
 * Fountainhead `/doc/file` page component
 * @class FountainheadPages.File
 * @constructor
 * @extends FountainheadPages.BasePage
 */
export default BasePage.extend({

  // Passed Properties
  // ---------------------------------------------------------------------------
  /**
   * JSON stringified file generated by documentation script.
   * @property file
   * @type {string}
   * @default ''
   */
  file: '',

  // Layout
  // ---------------------------------------------------------------------------
  layout: hbs`
    <h2 class='fh-page-header'>{{file.file}}</h2>
    {{{file.content}}}
  `
});
