import Component from 'ember-component';
import hbs from 'htmlbars-inline-precompile';

/**
 * File page wrapping component
 * @class FountainHead.File
 * @constructor
 * @extends Ember.Component
 */
export default Component.extend({

  /**
   * JSON stringified file generated by documentation script.
   * @property file
   * @type {string}
   * @default ''
   */
  file: '',

  // Layout
  // ---------------------------------------------------------------------------
  layout: hbs`
    <h1>File Contents:</h1>
    {{{file.content}}}
  `
});
